### ISSUE TITLE
Error With Start App

### ISSUE THREAD

**Issue by pkeller3** [epicweb-dev/testing-web-apps#10]
When I click `Start App` in the browser, the view changes to show `Unexpected Server Error`

In the console I see:
```
[exercises__sep__01.e2e__sep__01.solution.init:7001] Loading environment variables from .env
[exercises__sep__01.e2e__sep__01.solution.init:7001] 
[exercises__sep__01.e2e__sep__01.solution.init:7001] 💿 Built in 4.4s
[exercises__sep__01.e2e__sep__01.solution.init:7001] 
Error: Timed out waiting for: http://localhost:7001
    at /Users/pkeller/dev/testing-web-apps/node_modules/wait-on/lib/wait-on.js:132:31
    at doInnerSub (/Users/pkeller/dev/testing-web-apps/node_modules/rxjs/src/internal/operators/mergeInternals.ts:71:15)
    at outerNext (/Users/pkeller/dev/testing-web-apps/node_modules/rxjs/src/internal/operators/mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (/Users/pkeller/dev/testing-web-apps/node_modules/rxjs/src/internal/operators/OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (/Users/pkeller/dev/testing-web-apps/node_modules/rxjs/src/internal/Subscriber.ts:75:12)
    at AsyncAction.<anonymous> (/Users/pkeller/dev/testing-web-apps/node_modules/rxjs/src/internal/observable/timer.ts:173:20)
    at AsyncAction._execute (/Users/pkeller/dev/testing-web-apps/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:120:12)
    at AsyncAction.execute (/Users/pkeller/dev/testing-web-apps/node_modules/rxjs/src/internal/scheduler/AsyncAction.ts:95:24)
    at AsyncScheduler.flush (/Users/pkeller/dev/testing-web-apps/node_modules/rxjs/src/internal/scheduler/AsyncScheduler.ts:40:27)
    at listOnTimeout (node:internal/timers:569:17)
[exercises__sep__01.e2e__sep__01.solution.init:7001] HEAD / 500 109 - 10379.069 ms
[exercises__sep__01.e2e__sep__01.solution.init:7001] 
[exercises__sep__01.e2e__sep__01.solution.init:7001] HEAD / 500 109 - 10447.925 ms
[exercises__sep__01.e2e__sep__01.solution.init:7001] 
``` 

I cloned and ran the `setup` script this morning (05/03/2023) and I am pointed at commit `abf38e895`.

OS: macOS 12.6
node: v18.16.0
npm: 9.5.1

**Comment by pkeller3** [comment]
Not sure what changed, but I ran `setup` and `start` again and now it's working.
