### ISSUE TITLE
rocket rental exercises not working inside workshop-app

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/testing-web-apps#3]
I can not run any of rocket rental exercises inside workshop-app

after applying a workaround for #1 by moving `index.module.css` to styls
the app work when started normally from the terminal but not inside workshop-app

<details>
  <summary>terminal log</summary>
  
  ```
🐨  Let's get learning!
Local:            http://localhost:5639
On Your Network:  http://10.100.102.21:5639
Press Ctrl+C to stop
[01.e2e.01.problem.init:6001]
[01.e2e.01.problem.init:6001] > dev
[01.e2e.01.problem.init:6001] > cross-env NODE_ENV=development run-p dev:*
[01.e2e.01.problem.init:6001]
[01.e2e.01.problem.init:6001]
[01.e2e.01.problem.init:6001]
[01.e2e.01.problem.init:6001] > dev:server
[01.e2e.01.problem.init:6001] > tsx watch --clear-screen=false --ignore "app/**" --ignore "build/**" --ignore "node_modules/**" ./index.js
[01.e2e.01.problem.init:6001]
[01.e2e.01.problem.init:6001]
[01.e2e.01.problem.init:6001]
[01.e2e.01.problem.init:6001] > dev:remix
[01.e2e.01.problem.init:6001] > cross-env PORT="" remix dev
[01.e2e.01.problem.init:6001]
[01.e2e.01.problem.init:6001]
[01.e2e.01.problem.init:6001] Loading environment variables from .env
[01.e2e.01.problem.init:6001]
[01.e2e.01.problem.init:6001] 💿 Built in 3.4s
[01.e2e.01.problem.init:6001]
Error: Timed out waiting for: http://localhost:6001
    at C:\projects\kcd-apps\testing-web-apps\node_modules\wait-on\lib\wait-on.js:132:31
    at doInnerSub (C:\projects\kcd-apps\testing-web-apps\node_modules\rxjs\src\internal\operators\mergeInternals.ts:71:15)
    at outerNext (C:\projects\kcd-apps\testing-web-apps\node_modules\rxjs\src\internal\operators\mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (C:\projects\kcd-apps\testing-web-apps\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (C:\projects\kcd-apps\testing-web-apps\node_modules\rxjs\src\internal\Subscriber.ts:75:12)
    at AsyncAction.<anonymous> (C:\projects\kcd-apps\testing-web-apps\node_modules\rxjs\src\internal\observable\timer.ts:173:20)
    at AsyncAction._execute (C:\projects\kcd-apps\testing-web-apps\node_modules\rxjs\src\internal\scheduler\AsyncAction.ts:120:12)
    at AsyncAction.execute (C:\projects\kcd-apps\testing-web-apps\node_modules\rxjs\src\internal\scheduler\AsyncAction.ts:95:24)
    at AsyncScheduler.flush (C:\projects\kcd-apps\testing-web-apps\node_modules\rxjs\src\internal\scheduler\AsyncScheduler.ts:40:27)
    at listOnTimeout (node:internal/timers:569:17)
  ```

</details>

**Comment by onemen** [comment]
I was so focused on Remix that i did not noticed that the express server did not start
look like the issue from the changes to the file `exercises/_EXERCISENUMBER_/_STEPNUMBER_/server/index.ts`

**Comment by onemen** [comment]
it should be fixed by https://github.com/epicweb-dev/kcdshop/commit/1ffa3de22f8dfaa7d308902b297f475f037e38b4
