### ISSUE TITLE
Errors when starting apps

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/testing-web-apps#4]
with the latest workshop-app v1.33.0, this error message appears many times until remix build finished:

<details>
<summary><b>Error: Cannot find module build</b></summary>

```shell
[playground:4000] Error: Cannot find module 'C:\projects\kcd-apps\testing-web-apps\playground\build'
[playground:4000] Require stack:
[playground:4000] - C:\projects\kcd-apps\testing-web-apps\playground\server\index.ts
[playground:4000] - C:\projects\kcd-apps\testing-web-apps\playground\index.js
[playground:4000]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
[playground:4000]     at Function.u.default._resolveFilename (C:\projects\kcd-apps\testing-web-apps\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:1519)
[playground:4000]     at Function.Module._load (node:internal/modules/cjs/loader:920:27)
[playground:4000]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[playground:4000]     at require (node:internal/modules/cjs/helpers:110:18)
[playground:4000]     at C:\projects\kcd-apps\testing-web-apps\playground\server\index.ts:2:2126
[playground:4000]     at Layer.handle [as handle_request] (C:\projects\kcd-apps\testing-web-apps\node_modules\express\lib\router\layer.js:8:864)
[playground:4000]     at next (C:\projects\kcd-apps\testing-web-apps\node_modules\express\lib\router\route.js:8:1411)
[playground:4000]     at next (C:\projects\kcd-apps\testing-web-apps\node_modules\express\lib\router\route.js:8:1340)
[playground:4000]     at next (C:\projects\kcd-apps\testing-web-apps\node_modules\express\lib\router\route.js:8:1340)
```

</details>

in `web-app-fundamentals` you are using the following code to prevent this errors 
```ts
// wait for the build directory to exist before trying to require it
// this is necessary because the build directory is created by the
// build process, which is started by the dev process
async function getBuild(): Promise<ServerBuild> {
	let start = Date.now()
	while (Date.now() - start < 10000) {
		try {
			return require(BUILD_DIR)
		} catch (error: unknown) {
			if (
				error &&
				typeof error === 'object' &&
				'code' in error &&
				error.code !== 'MODULE_NOT_FOUND'
			) {
				throw error
			}
		}
		await new Promise(resolve => setTimeout(resolve, 100))
	}
	throw new Error(`Could not find build directory at ${BUILD_DIR}`)
}
```

i can push a PR to add this function call back

when applying `SET TO PLAYGROUND` over running playground, sometimes i get this error messages:

<details>
<summary><b>Remix css plugins errors</b></summary>

```shell
[playground:4000] ✘ [ERROR] [plugin css-bundle-update-plugin] Cannot call "resolve" on an inactive build
[playground:4000]
[playground:4000]     ../node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:1261:21:
[playground:4000]       1261 │               reject(new Error(error));
[playground:4000]            ╵                      ^
[playground:4000]
[playground:4000]     at C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:1261:22
[playground:4000]     at responseCallbacks.<computed> (C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:694:9)
[playground:4000]     at handleIncomingPacket (C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:747:9)
[playground:4000]     at Socket.readFromStdout (C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:670:7)
[playground:4000]     at Socket.emit (node:events:513:28)
[playground:4000]     at addChunk (node:internal/streams/readable:324:12)
[playground:4000]     at readableAddChunk (node:internal/streams/readable:297:9)
[playground:4000]     at Readable.push (node:internal/streams/readable:234:10)
[playground:4000]     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[playground:4000]
[playground:4000]   This error came from the "onResolve" callback registered here:
[playground:4000]
[playground:4000]     ../node_modules/@remix-run/dev/dist/compiler/plugins/cssBundleUpdatePlugin.js:37:12:
[playground:4000]       37 │       build.onResolve({
[playground:4000]          ╵             ~~~~~~~~~
[playground:4000]
[playground:4000]     at setup (C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\dist\compiler\plugins\cssBundleUpdatePlugin.js:37:13)
[playground:4000]     at handlePlugins (C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:1276:21)
[playground:4000]
[playground:4000]   The plugin "css-bundle-update-plugin" was triggered by this import
[playground:4000]
[playground:4000]     browser-route-module:root.tsx?browser:23:30:
[playground:4000]       23 │ import { cssBundleHref } from "@remix-run/css-bundle";
[playground:4000]          ╵                               ~~~~~~~~~~~~~~~~~~~~~~~
[playground:4000]
[playground:4000]  ✘ [ERROR] [plugin css-modules-plugin] Cannot call "resolve" on an inactive build
[playground:4000]
[playground:4000]     ../node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:1261:21:
[playground:4000]       1261 │               reject(new Error(error));
[playground:4000]            ╵                      ^
[playground:4000]
[playground:4000]     at C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:1261:22
[playground:4000]     at responseCallbacks.<computed> (C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:694:9)
[playground:4000]     at handleIncomingPacket (C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:747:9)
[playground:4000]     at Socket.readFromStdout (C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:670:7)
[playground:4000]     at Socket.emit (node:events:513:28)
[playground:4000]     at addChunk (node:internal/streams/readable:324:12)
[playground:4000]     at readableAddChunk (node:internal/streams/readable:297:9)
[playground:4000]     at Readable.push (node:internal/streams/readable:234:10)
[playground:4000]     at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
[playground:4000]
[playground:4000]   This error came from the "onResolve" callback registered here:
[playground:4000]
[playground:4000]     ../node_modules/@remix-run/dev/dist/compiler/plugins/cssModulesPlugin.js:44:12:
[playground:4000]       44 │       build.onResolve({
[playground:4000]          ╵             ~~~~~~~~~
[playground:4000]
[playground:4000]     at setup (C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\dist\compiler\plugins\cssModulesPlugin.js:44:13)
[playground:4000]     at async handlePlugins (C:\projects\kcd-apps\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:1318:9)
[playground:4000]
[playground:4000]   The plugin "css-modules-plugin" was triggered by this import
[playground:4000]
[playground:4000]     app/utils/forms.tsx:6:19:
[playground:4000]       6 │ import styles from './forms.module.css';
[playground:4000]         ╵                    ~~~~~~~~~~~~~~~~~~~~
[playground:4000]
[playground:4000]
[playground:4000]
[playground:4000] Build failed with 2 errors:
[playground:4000] ../node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:1261:21: ERROR: [plugin: css-bundle-update-plugin] Cannot call "resolve" on an inactive build
[playground:4000] ../node_modules/@remix-run/dev/node_modules/esbuild/lib/main.js:1261:21: ERROR: [plugin: css-modules-plugin] Cannot call "resolve" on an inactive build
[playground:4000]
[playground:4000] 💿 Rebuilt in 3.1s
[playground:4000] 💿 Waiting for http://10.100.102.21:4000...
```

</details>

**Comment by onemen** [comment]
one more issue
when running playground app on on windows 10, i see  `GET /__REMIX_ASSETS_MANIFEST 200 ` message all the time, it never stops.

<details>
<summary><b>GET /__REMIX_ASSETS_MANIFEST 200 run all the time</b></summary>

```shell
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 75.208 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 68.858 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 71.920 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 71.780 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 73.963 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 70.691 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 70.441 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 68.668 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 70.386 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 68.809 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 67.433 ms
[playground:4000]
[playground:4000] GET /__REMIX_ASSETS_MANIFEST 200 - - 66.583 ms
```

</details>
