### ISSUE TITLE
Error: Cannot find module 'C:\Temp\testing-web-apps\playground\build'

### ISSUE THREAD

**Issue by hemagupta77** [epicweb-dev/testing-web-apps#7]
I followed the installation procedure and could install and do the npm start. But when I am trying to run any test from the browser, I get below errors:

```
Error: Cannot find module 'C:\Temp\testing-web-apps\playground\build'
[playground:4000] Require stack:
[playground:4000] - C:\Temp\testing-web-apps\playground\server\index.ts
[playground:4000] - C:\Temp\testing-web-apps\playground\index.js
[playground:4000]     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
[playground:4000]     at Function.u.default._resolveFilename (C:\Temp\testing-web-apps\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:1519)
[playground:4000]     at Function.Module._load (node:internal/modules/cjs/loader:920:27)
[playground:4000]     at Module.require (node:internal/modules/cjs/loader:1141:19)
[playground:4000]     at require (node:internal/modules/cjs/helpers:110:18)
[playground:4000]     at C:\Temp\testing-web-apps\playground\server\index.ts:2:2126
[playground:4000]     at Layer.handle [as handle_request] (C:\Temp\testing-web-apps\node_modules\express\lib\router\layer.js:8:864)
[playground:4000]     at next (C:\Temp\testing-web-apps\node_modules\express\lib\router\route.js:8:1411)
[playground:4000]     at next (C:\Temp\testing-web-apps\node_modules\express\lib\router\route.js:8:1340)
[playground:4000]     at next (C:\Temp\testing-web-apps\node_modules\express\lib\router\route.js:8:1340)
[playground:4000]
Error: Timed out waiting for: http://localhost:4000
    at C:\Temp\testing-web-apps\node_modules\wait-on\lib\wait-on.js:132:31
    at doInnerSub (C:\Temp\testing-web-apps\node_modules\rxjs\src\internal\operators\mergeInternals.ts:71:15)
    at outerNext (C:\Temp\testing-web-apps\node_modules\rxjs\src\internal\operators\mergeInternals.ts:53:58)
    at OperatorSubscriber._this._next (C:\Temp\testing-web-apps\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:70:13)
    at OperatorSubscriber.Subscriber.next (C:\Temp\testing-web-apps\node_modules\rxjs\src\internal\Subscriber.ts:75:12)
    at AsyncAction.<anonymous> (C:\Temp\testing-web-apps\node_modules\rxjs\src\internal\observable\timer.ts:173:20)
    at AsyncAction._execute (C:\Temp\testing-web-apps\node_modules\rxjs\src\internal\scheduler\AsyncAction.ts:120:12)
    at AsyncAction.execute (C:\Temp\testing-web-apps\node_modules\rxjs\src\internal\scheduler\AsyncAction.ts:95:24)
    at AsyncScheduler.flush (C:\Temp\testing-web-apps\node_modules\rxjs\src\internal\scheduler\AsyncScheduler.ts:40:27)
    at listOnTimeout (node:internal/timers:569:17)
[playground:4000] 
[playground:4000]
[playground:4000] X [ERROR] [plugin browser-route-modules] C:\Temp\testing-web-apps\playground\app\routes\index.module.css: Unexpected token (1:0)
[playground:4000]
[playground:4000] > 1 | .statsDistance {
[playground:4000]     | ^
[playground:4000]   2 |         background: linear-gradient(
[playground:4000]   3 |                 269.6deg,
[playground:4000]   4 |                 #657cff 13.84%,
[playground:4000]
[playground:4000]   This error came from the "onLoad" callback registered here:
[playground:4000]
[playground:4000]     ../node_modules/@remix-run/dev/dist/compiler/plugins/browserRouteModulesPlugin_v2.js:122:12:
[playground:4000]       122 │       build.onLoad({
[playground:4000]           ╵             ~~~~~~
[playground:4000]
[playground:4000]     at setup (C:\Temp\testing-web-apps\node_modules\@remix-run\dev\dist\compiler\plugins\browserRouteModulesPlugin_v2.js:122:13)
[playground:4000]     at handlePlugins (C:\Temp\testing-web-apps\node_modules\@remix-run\dev\node_modules\esbuild\lib\main.js:1276:21)
[playground:4000]
[playground:4000]
[playground:4000]
[playground:4000] 💿 Built in 2.8s
[playground:4000]
[playground:4000] Build failed with 1 error:
[playground:4000] error: C:\Temp\testing-web-apps\playground\app\routes\index.module.css: Unexpected token (1:0)
[playground:4000]
[playground:4000] > 1 | .statsDistance {
[playground:4000]     | ^
[playground:4000]   2 |         background: linear-gradient(
[playground:4000]   3 |                 269.6deg,
[playground:4000]   4 |                 #657cff 13.84%,
```

I have my workshop tomorrow so it'll be helpful if I can get a response in time.

**Comment by kentcdodds** [comment]
This should be fixed now. Thanks! See you tomorrow!
